spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://meongmory-db.cjiriihixouh.ap-northeast-2.rds.amazonaws.com:3306/meongmory?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: meongmory
    password: meongmory1234!

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
