spring:
  application:
    name: meongmory

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??
    url: jdbc:mysql://meongmory-db.cjiriihixouh.ap-northeast-2.rds.amazonaws.com:3306/meongmoryDB?serverTimezone=Asia/Seoul
    username: meongmory
    password: meongmeongeeee12345!
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug


